name: Style Checks
on: [push, pull_request]

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install black
      id: install
      run : |
        pip install shyaml
        blackv=$(cat .pre-commit-config.yaml | shyaml get-value repos.3.rev | xargs)
        pip install black==$blackv
    - name: check
      id: black
      run: |
        black --version
        black --check --diff pyVBRc/
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install isort
      id: install
      run : |
        pip install shyaml
        isortv=$(cat .pre-commit-config.yaml | shyaml get-value repos.4.rev | xargs)
        pip install isort==$isortv
    - name: check
      id: isort
      run: |
        isort --version-number
        isort pyVBRc --check --diff
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install flake8
      id: install
      run : |
        pip install shyaml
        flk8v=$(cat .pre-commit-config.yaml | shyaml get-value repos.5.rev | xargs)
        pip install flake8==$flk8v
    - name: check
      id: flake8
      run: |
        flake8 --version
        flake8 pyVBRc/
